2019-08-17 00:36:34,266 ERROR: Exception on /index [GET] [in /home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/alexey/PycharmProjects/flask_site/app/main/routes.py", line 46, in index
    prev_url=prev_url)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/alexey/PycharmProjects/flask_site/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/alexey/PycharmProjects/flask_site/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/alexey/PycharmProjects/flask_site/app/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/alexey/PycharmProjects/flask_site/app/templates/index.html", line 11, in block "app_content"
    {% include '_post.html' %}
  File "/home/alexey/PycharmProjects/flask_site/app/templates/_post.html", line 4, in top-level template code
    <a href="{{ url_for('user', username=post.author.username) }}">
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2007, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'main.user' instead?
2019-08-17 00:39:01,036 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:74]
2019-08-17 00:39:36,007 ERROR: Exception on /user/Pit [GET] [in /home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/alexey/PycharmProjects/flask_site/app/main/routes.py", line 76, in user
    next_url=next_url, prev_url=prev_url)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/alexey/PycharmProjects/flask_site/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/alexey/PycharmProjects/flask_site/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/alexey/PycharmProjects/flask_site/app/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/alexey/PycharmProjects/flask_site/app/templates/user.html", line 15, in block "app_content"
    <p><a href="{{ url_for('edit_profile') }}">{{ _('Edit your profile') }}</a></p>
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2007, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'edit_profile'. Did you mean 'main.edit_profile' instead?
2019-08-17 00:41:10,465 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:74]
2019-08-17 12:44:16,672 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:74]
2019-08-17 12:49:01,182 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:74]
