2019-08-17 00:26:45,715 ERROR: Exception on /auth/reset_password_request [POST] [in /home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alexey/PycharmProjects/flask_site/app/auth/routes.py", line 60, in reset_password_request
    send_password_reset_email(user)
  File "/home/alexey/PycharmProjects/flask_site/app/auth/email.py", line 7, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/home/alexey/PycharmProjects/flask_site/app/models.py", line 58, in get_reset_password_token
    return jwt.encode({'reset_password': self.id, 'exp': time() + expires_in}, app.config['SECRET_KEY'],
NameError: name 'app' is not defined
2019-08-17 00:29:11,533 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:74]
2019-08-17 00:29:24,549 ERROR: Exception on /auth/reset_password_request [POST] [in /home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alexey/PycharmProjects/flask_site/app/auth/routes.py", line 60, in reset_password_request
    send_password_reset_email(user)
  File "/home/alexey/PycharmProjects/flask_site/app/auth/email.py", line 7, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/home/alexey/PycharmProjects/flask_site/app/models.py", line 58, in get_reset_password_token
    return jwt.encode({'reset_password': self.id, 'exp': time() + expires_in}, app.config['SECRET_KEY'],
NameError: name 'app' is not defined
2019-08-17 00:31:21,787 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:74]
2019-08-17 00:31:49,807 ERROR: Exception on /auth/reset_password_request [POST] [in /home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alexey/PycharmProjects/flask_site/app/auth/routes.py", line 60, in reset_password_request
    send_password_reset_email(user)
  File "/home/alexey/PycharmProjects/flask_site/app/auth/email.py", line 10, in send_password_reset_email
    sender=app.config['ADMINS'][0],
NameError: name 'app' is not defined
2019-08-17 00:32:49,198 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:74]
2019-08-17 00:33:16,770 ERROR: Exception on /auth/reset_password_request [POST] [in /home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alexey/PycharmProjects/flask_site/app/auth/routes.py", line 60, in reset_password_request
    send_password_reset_email(user)
  File "/home/alexey/PycharmProjects/flask_site/app/auth/email.py", line 12, in send_password_reset_email
    text_body=render_template('email/reset_password.txt', user=user, token=token),
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/alexey/PycharmProjects/flask_site/app/templates/email/reset_password.txt", line 5, in top-level template code
    {{ url_for('reset_password', token=token, _external=True) }}
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2007, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'auth.reset_password' instead?
2019-08-17 00:35:11,283 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:74]
