2019-08-26 09:10:42,494 ERROR: Exception on /index [POST] [in /home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/alexey/PycharmProjects/flask_site/app/main/routes.py", line 34, in index
    db.session.commit()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 501, in commit
    self.session.dispatch.after_commit(self.session)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 259, in __call__
    fn(*args, **kw)
  File "/home/alexey/PycharmProjects/flask_site/app/models.py", line 35, in after_commit
    add_to_index(obj.__tablenane__, obj)
AttributeError: 'Post' object has no attribute '__tablenane__'
2019-08-26 09:10:55,699 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:77]
2019-08-26 09:11:12,117 ERROR: Exception on / [POST] [in /home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/alexey/PycharmProjects/flask_site/app/main/routes.py", line 34, in index
    db.session.commit()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 501, in commit
    self.session.dispatch.after_commit(self.session)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 259, in __call__
    fn(*args, **kw)
  File "/home/alexey/PycharmProjects/flask_site/app/models.py", line 35, in after_commit
    add_to_index(obj.__tablenane__, obj)
AttributeError: 'Post' object has no attribute '__tablenane__'
2019-09-14 10:27:46,774 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:77]
2019-09-14 10:30:24,447 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:77]
2019-09-14 12:23:34,328 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:77]
2019-09-14 13:35:22,759 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:77]
2019-09-14 13:39:44,352 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:77]
2019-09-14 13:41:54,749 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:77]
2019-09-14 13:44:05,098 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:77]
2019-09-14 13:44:20,911 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:77]
2019-09-14 13:44:28,861 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:77]
2019-09-14 13:51:44,548 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:77]
2019-09-14 16:14:17,440 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:77]
2019-09-14 16:16:57,263 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:77]
2019-09-14 16:17:10,562 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:77]
2019-09-15 11:45:07,980 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:77]
2019-09-15 11:45:57,552 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:77]
2019-09-15 12:32:26,985 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:77]
2019-09-15 12:50:52,585 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:77]
2019-09-20 18:31:53,900 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:77]
2019-09-20 18:32:20,790 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:77]
2019-09-21 12:33:39,439 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:81]
2019-09-21 12:40:12,753 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:81]
2019-09-21 12:43:14,216 INFO: Microblog startup [in ./app/__init__.py:81]
2019-09-21 12:45:05,204 ERROR: Unhandled exception [in ./app/tasks.py:48]
Traceback (most recent call last):
  File "./app/tasks.py", line 45, in export_posts
    sync=True)
  File "./app/email.py", line 21, in send_email
    mail.send(msg)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask_mail.py", line 158, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
  File "/usr/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2019-09-21 12:47:38,965 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:81]
2019-09-21 12:48:03,767 INFO: Microblog startup [in ./app/__init__.py:81]
2019-09-21 12:49:54,505 ERROR: Unhandled exception [in ./app/tasks.py:48]
Traceback (most recent call last):
  File "./app/tasks.py", line 45, in export_posts
    sync=True)
  File "./app/email.py", line 21, in send_email
    mail.send(msg)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask_mail.py", line 158, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
  File "/usr/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2019-09-21 12:54:57,607 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:81]
2019-09-21 12:56:27,825 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:81]
2019-09-21 12:57:02,858 INFO: Microblog startup [in ./app/__init__.py:81]
